### ISSUE TITLE
Restarting a run

### ISSUE THREAD

**Issue by dipto4** [nbodyx/Nbody6ppGPU#15]
Hello,
I went through the manual but I am still not sure how to restart a previously stopped run. Any help with that would be really appreciated. 

Thank you.

**Comment by lwang-astro** [comment]
Hi,

 

The restarting example of input file is shown in the page 20 in the manual.

There is one mistake there is that the restart file name is ‘comm.1’ instead of ‘fort.1’

The comm.1 can be obtained by copying/renaming comm.2 or comm.2_[num] from the stopped run.

With a restart input file and comm.1 in the same directory, you can run 

nbody6++.** < [restart input file] 

to restart the run.

 

Bests.

Long

**Comment by dipto4** [comment]
Thank you!
