### ISSUE TITLE
Crash on GPU

### ISSUE THREAD

**Issue by minzastro** [nbodyx/Nbody6ppGPU#3]
The code compiles, but crashes on N256.input sample with:
```
nbody6++.avx.gpu: ../src/Main/gpunb.velocity.cu:72: Jparticle::Jparticle(double, double*, double*): Assertion `(xj[0]) == (xj[0])' failed.

Program received signal SIGABRT: Process abort signal.
```

I run with --disable-mpi
```
configure: ----------------------Configure Summary--------------------
configure: --Features:
configure:      Using MPI:      no
configure:      Using GPU:      yes
configure:      CUDA version:   8.0
configure:      Using SIMD:     avx
configure:      mcmodel:        medium
configure:      OpenMP option:  -fopenmp
configure:      Debug mode:     no
configure:      HDF5 format:    no
configure:      TT package:     no
configure: --Compilers:
configure:      C++ compiler:      g++
configure:      Fortran compiler:  gfortran
configure:      CUDA compiler:     nvcc
configure: --Targets:
configure:      Program name:   nbody6++.avx.gpu
configure:      Extra tools:    no
configure:      Install path:   NONE
configure: --Parameters:
configure:      NMAX:           24576
configure:      KMAX:           8192
configure:      LMAX:           400
configure:      MMAX:           512
configure: -----------------------------------------------------------
```

It looks that the problem appears on initial steps when the scaling of the data is done. Looks like CALL ENERGY(.true.) in SCALE sets POT variable to NaN when GPU is used.

**Comment by lwang-astro** [comment]
There is no sample name called N256.input in sample directory. Did you modified the input file? What are the input parameters used in your test?

**Comment by minzastro** [comment]
I took N16k.input and replaced 16000 with 265 on the line 2, just to speed up things a bit for testing...

**Comment by lwang-astro** [comment]
I did not reproduce your assertion error. But Just change 16000 to 256 will lead to "calculation halt" due to large energy error. 
Simply change N usually did not work. Since when you change N, the star cluster density also change, together with the crossing time and relaxation time. In this case, you also need to modify other parameters to adjust the system. 
Especially, the initial neighbor radius guess (RS0) should be modified. I prefer to use the formula (<N_b>/N)**(1/3) where <N_b> is expected averaged neighbor number. It is a rough guess, not always work. 

Anyway, since you already have GPU, 256 particle makes no sense to use GPU. 16k actually is suitable for a GPU version test
