### ISSUE TITLE
Error in cuda_share.h

### ISSUE THREAD

**Issue by ElizabethMorh** [nbodyx/Nbody6ppGPU#31]
I am using a computer with Intel E5-2670v1 and GPU NVIDIA M2090 to run the code. While running the program for a case of 32K particles, I am getting the following error:

 ../include/cuda_share.h:34: Jparticle::Jparticle(double, double*, double*): Assertion `(xj[0]) == (xj[0])' failed.

**Comment by lwang-astro** [comment]
Check whether you have used too large rs0 or use  --with-par=b1m in configure.

**Comment by ElizabethMorh** [comment]
I tried changing the rs0 from 0.1 to 0.04 and didn’t worked, later from 0.04 to 0.01 and 0.005 and I still get the same error.

Then I changed the configuration using --with-par=b1m and I ran simulations for the same four rs0 values but I'm getting the same error for every case.

**Comment by lwang-astro** [comment]
If you switch off using AVX or GPU, can the code works? 
I cannot reproduce such situation in my local machine. 

By the way, recently I am released the new code PeTar, https://github.com/lwang-astro/PeTar, 
This can do what NB6++GPU can do, and is probably better (https://arxiv.org/abs/2006.16560) on performance and data analysis. If this problem is difficult to solve or there is no special reason that you want to use NB6++GPU only, I would recommend to try this new code. In the GitHub page, the README show the details how to install and use petar and the data analysis tool. My support for the new code will be much better.
