### ISSUE TITLE
Run on GPU

### ISSUE THREAD

**Issue by Eimantas10** [nbodyx/Nbody6ppGPU#34]
Hello,

I'm a beginner with Nbody simulations, but I cannot find the information of how to run the simulation on GPU.
CPU, CPU with MPI works perfect. I have CUDA installed, so how can I run a simulation full on GPU ?

**Comment by mdelorme** [comment]
Hi, 

The GPU is enabled by default so your runs should already be running on GPU :)

**Comment by Eimantas10** [comment]
Okay, but please clarify if I'm wrong. Single node calculations use mostly CPU memory, because I checked and GPU memory usage was between 95-135 Mb. But when I run parallel calculations, with every node I use GPU. For example, 8 parallel nodes 8*135 Mb ~ 1 Gb of GPU memory usage. To sum up, CPU and GPU works together, right ? And if I want to allocate more memory to GPU I should use parallel calculations, right ?

**Comment by mdelorme** [comment]
Hi again, 

Yes, CPU and GPU work together, the GPU is only used for a couple of operations (mainly the O(N^2) direct summation on on regular forces). You cannot control how much data is sent to the GPUs unfortunately, since it will be only problem dependent. The quantity of data allocated on the GPU will be proportional to the maximum number of points in the system (NBMAX) and other things : see for instance [this method](https://github.com/nbodyx/Nbody6ppGPU/blob/master/src/Main/gpunb.gpu.cu#L592).

So the only impact you will have on the amount of memory used on the GPU will be the maximum constants set by the configuration script (or in params.h).

Not sure that answers your question, but feel free to ask more.

**Comment by Eimantas10** [comment]
Thank You so much for the clarification. That would be all.
