### ISSUE TITLE
Understanding simulation box size

### ISSUE THREAD

**Issue by efrubin** [nbodyx/Nbody6ppGPU#6]
I am trying to understand more rigorously how some simulations I'm running work.  

My understanding is that a cluster is placed inside of a box and that the relative sizes of the cluster and box should be important, after all, if the cluster runs up against the edge of the box then particles may be expelled from the system simply through thermal motion.   I can also tell that the physical size of the system is left as a free parameter from one of the inputs (letting you say how many Nbody radius units correspond to a parsec.)  But from reading the manual and searching the code, I don't understand how this box size is set, and whether it is set as a fixed multiple of the cluster radius or whether it is a free parameter.

I would really appreciate if one of the project maintainers could clarify this.

**Comment by mdelorme** [comment]
I am not a maintainer of the project, but I've fiddled enough with the code to provide an element of answer to your question (really late, but that might still be helpful for others).

NBody6++ has no box size per se. There is no need for a box since the code is purely Lagrangian, the particles are never exiting the domain unless you consider escapers which are treated in a very specific way in the code. The normalisations are here to make sure the code runs in NBody-units, which is a very specific set of units. In these units, you set G=1, the total mass of the system M=1 and the total energy of the system E = -1/4. The scaling length comes from this set of units.

When starting a simulation, you should see in the logs a line with all the conversion factors needed to get back to physical units. For example, on one of my sims :

`PHYSICAL SCALING:    R* =   1.000000000000E+00  M* =   3.308153533811E+03  V* =   3.772005295627E+00  T* =   2.596974589648E-01  <M> =   6.616307067623E-01  SU =   4.436632063264E+07`

R* is the length scaling (so you multiply by it to get from NBody units to pc), M* the mass, etc.

Hope that helps a little.
